### ISSUE TITLE
Add steps to setup a local test version in README

### ISSUE THREAD

**Issue by roshan1337d** [roshan1337d/coding-contests-companion#1]
## What needs to be explained

- [ ] Creating a bot account on the [discord developers page](https://discord.com/developers).
- [ ] Inviting the bot to a testing server.
- [ ] Creating the [config.json](https://github.com/roshan1337d/coding-contests-companion/blob/master/CONTRIBUTING.md#configjson) file.
- [ ] Cloning this repo, installing the packages, and starting the bot.

**Comment by Dun-sin** [comment]
Can I work on this?

**Comment by Souvik-Nayak** [comment]
I want to work on this issue !

**Comment by roshan1337d** [comment]
@Souvik-Nayak assigned this issue to you.

@Dun-sin Souvik was the one who proposed for this first through the hacktoberfest discord, so feels right to assign it to him first.

Happy hacktober 🚀

**Comment by roshan1337d** [comment]
@Souvik-Nayak you still want to work on this one?

**Comment by Souvik-Nayak** [comment]
I am working on this issue midway completed !

**Comment by Souvik-Nayak** [comment]
> ## What needs to be explained
> * [X]  Creating a bot account on the [discord developers page](https://discord.com/developers).
> * [X]  Inviting the bot to a testing server.
> * [X]  Creating the [config.json](https://github.com/roshan1337d/coding-contests-companion/blob/master/CONTRIBUTING.md#configjson) file.
> * [X]  Cloning this repo, installing the packages, and starting the bot.

Done all the subtopics as mentioned !
