### ISSUE TITLE
Changing bot status/activity with help command and server count

### ISSUE THREAD

**Issue by roshan1337d** [roshan1337d/coding-contests-companion#10]
## What needs to be done

Make the bot status/activity switch between `Watching /help for user guide` and `Watching {server_count} servers` every 15 seconds.

## Tips

- Set a 15 seconds loop using setInterval [here](https://github.com/roshan1337d/coding-contests-companion/blob/233182d576380babc633c47c902d96eca951a759/index.js#L62)
- Use `client.guilds.cache.size` for the server count
- Use [setActivity](https://discord.js.org/#/docs/discord.js/main/class/ClientUser?scrollTo=setActivity) with `ActivityType.Watching` type for setting the status/activity.

**Comment by gaurangk19** [comment]
Hey @roshan1337d, I would like to contribute in this. I am new to the open source world but I definitely am willing to learn and grow:-)

**Comment by roshan1337d** [comment]
@gaurangk19 I see you have also asked to be assigned for another issue, which one do you want to work on first? I want to keep one open for someone else. You can have the other one after completing one of them if the other one is still not assigned to someone else by then.

**Comment by gaurangk19** [comment]
I will work on "Server joining message" issue. You can consider someone else for this issue till I complete the other one.

**Comment by cimok2000** [comment]
Hi I can totally pick this one up and have it done quickly.

**Comment by DevilzzNikhil** [comment]
@roshan1337d  please assign this to me i would be happy to do this

**Comment by roshan1337d** [comment]
@cimok2000 assigned this to you

@DevilzzNikhil Assigning it to cimok on first come basis. Incase s/he isn't able to complete this, I will assign it to you.

Happy hacktober 🚀

**Comment by DevilzzNikhil** [comment]
@roshan1337d  can u raise some more issue so that i can contribute ??

**Comment by roshan1337d** [comment]
@cimok2000 you still on this, right?

**Comment by DevilzzNikhil** [comment]
@roshan1337d  can i work on this ??

**Comment by roshan1337d** [comment]
Sure @DevilzzNikhil
Assigned this to you

**Comment by DevilzzNikhil** [comment]
Hey Roshan. I am also sophomore at iit bhu (ECE) after hacktoberfest can we
work on a project together? If u not mind

**Comment by roshan1337d** [comment]
I am from IIIT Bhubaneswar which is a different college from IIT BHU. But I am open to collaborating, and you can reach me out on my [LinkedIn](https://www.linkedin.com/in/roshandash) for personal messaging.

**Comment by DevilzzNikhil** [comment]
@roshan1337d  done with code but still one doubt 
watching /help for user guide is just a string or /help has some work here ??

**Comment by DevilzzNikhil** [comment]
@roshan1337d  any more issue you can raise so that we can contribute
