### ISSUE TITLE
Add support for AtCoder

### ISSUE THREAD

**Issue by roshan1337d** [roshan1337d/coding-contests-companion#2]
## What needs to be done

Create an `atCoder` function in the [scraping.js](https://github.com/roshan1337d/coding-contests-companion/blob/master/utility/scraping.js) file which returns an array of contest details from the [AtCoder contests page](https://atcoder.jp/contests). You can use Axios to get the contest page HTML content and use jsDom to query for the contest details. The contest data should be returned in the following format:

```js
{
    name: 'name_of_contest',
    url: 'link_to_the_contest',
    start: start_time_in_epoch_format,
    duration: duration_in_seconds
}
```

**Comment by B4CKF1SH** [comment]
I'd love to work on this :)

**Comment by roshan1337d** [comment]
PR submitted and approved
