### ISSUE TITLE
Update Contest Platforms

### ISSUE THREAD

**Issue by slayeh17** [roshan1337d/coding-contests-companion#23]
I would like to update the constest platforms because google kickstart has been discontinued and it will always show `No scheduled contests`.

1. I would like to remove `Google Kickstart`
2. I would like to add `Geeks for geek` weekly coding contest

**Comment by slayeh17** [comment]
> hello @slayeh17 , are you working on this issue ?

Nope I wasn't assigned but if you like go ahead. I have my final sem exam coming up so I won't be able to focus on this issue.

Ask the maintainer to assign you.

Cheers

**Comment by RJ025** [comment]
@slayeh17  thank you so much for informing.
yeah no problem in that can you help how you were going to approach this issue

**Comment by slayeh17** [comment]
> @slayeh17 thank you so much for informing. yeah no problem in that can you help how you were going to approach this issue

Yeah I was thinking of web scraping this site `https://practice.geeksforgeeks.org/contest/gfg-weekly-coding-contest-104` to get the dates and time as I did not find any API for GFG.

Then I would increment the contest number 104 to 105 to 106 ... until I get 404 error. 

I don't have much idea about web scraping so this idea might not work😅.

**Comment by RJ025** [comment]
@slayeh17  yeah actually I also don't have much idea about web scraping 😅
but yeah no problem in we can always learn it.
thank you so much for helping

**Comment by roshan1337d** [comment]
@RJ025 assigned you this issue.

I looked around GFG and did some work for you to make this easier. Use the below endpoint to find the upcoming contest details: https://practiceapi.geeksforgeeks.org/api/vr/events/?page_number=1&sub_type=all&type=contest

If you have any further doubts feel free to ask here or in the coding contest companion channel on GSSoC discord server. Best of luck 🚀

**Comment by RJ025** [comment]
Thank you @roshan1337d  for assigning me this issue and helping me 
actually I cant this channel on the discord

**Comment by RJ025** [comment]
hello @roshan1337d  
how to get Emoji Id in Contests.js file ?

**Comment by RJ025** [comment]
@roshan1337d  does bot have permission to USE EXTERNAL EMOJIS because I created a GFG emoji and entered the ID but bot can't fetch the contests menu

**Comment by roshan1337d** [comment]
@RJ025 invite the bot to the server having the GFG emoji and it should work then.
