### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by shraddha761** [roshan1337d/coding-contests-companion#26]
![Screenshot 2023-05-21 160801](https://github.com/roshan1337d/coding-contests-companion/assets/106100728/bef494f7-67b8-45d8-ad44-becd9c440902)

Adding this badges to readme makes it more attractive assign me this issue under GSSOC'23

**Comment by roshan1337d** [comment]
There are already a few PRs in review which have added in such badges. Feel free to create a new issue if you have some other suggestions. Happy GSSoC 🚀
