### ISSUE TITLE
Adding new platform for problem of the day 

### ISSUE THREAD

**Issue by p1yush** [roshan1337d/coding-contests-companion#29]
We can add gfg problem of the day also.
Please assign this to me, thank you.

**Comment by roshan1337d** [comment]
Hello @p1yush 

Someone is already working on including GFG through issue #23 

Feel free to open a new issue if you have more contest platforms in mind. Best of luck 🍀

**Comment by p1yush** [comment]
yes we can also add codestudio problem of the day
