### ISSUE TITLE
Add support for Google Kick Start

### ISSUE THREAD

**Issue by roshan1337d** [roshan1337d/coding-contests-companion#3]
## What needs to be done

Create a `kickStart` function in the [scraping.js](https://github.com/roshan1337d/coding-contests-companion/blob/master/utility/scraping.js) file which returns an array of contest details (next and upcoming rounds) from the [Google Kick Start contests page](https://codingcompetitions.withgoogle.com/kickstart/schedule). You can use Axios to get the contest page HTML content and use jsDom to query for the contest details. The contest data should be returned in the following format:

```js
{
    name: 'name_of_contest',
    url: 'link_to_the_contest',
    start: start_time_in_epoch_format,
    duration: duration_in_seconds
}
```

**Comment by SahilAnower** [comment]
I would like to work on this if available. Thanks.

**Comment by roshan1337d** [comment]
@SahilAnower Assigned this to you. Hold off on the submission until 1st of October if you want it to count towards the HacktoberFest 🚀

**Comment by SahilAnower** [comment]
Shall I use this? @roshan1337d , Many things are already done here, we don't have to brainstorm that much. If you permit, I shall use it.
[Kontest API](https://www.kontests.net/api)

**Comment by SahilAnower** [comment]
### So far

> Used Kontest API

![ezgif com-gif-maker](https://user-images.githubusercontent.com/49086583/193278898-e5ae84e7-1d5c-4dba-bfc2-f900a633109c.gif)

**Comment by roshan1337d** [comment]
This seems great @SahilAnower but I don't feel right about using a 3rd party api dependance for such a core service. If they stop providing it someday, we would either have to write our own stuff again, or use their codebase which is written with ruby that I have no experience with.

**Comment by SahilAnower** [comment]
Okay @roshan1337d. I will try that then

**Comment by roshan1337d** [comment]
@SahilAnower you still on this, right?
