### ISSUE TITLE
Updating contributing.md file

### ISSUE THREAD

**Issue by Abhinavcode13** [roshan1337d/coding-contests-companion#33]
please assign me this issue @roshan1337d

**Comment by roshan1337d** [comment]
What do you want to update?

**Comment by Audrey-me** [comment]
hi @roshan1337d, please i already made some updates on the file based on some of the instructions that was not stated out that got me confused, and it took a lot of time before I could figure it out.

I'm pretty sure with the updates I have done, it will make it easier for people to navigate through it
