### ISSUE TITLE
Add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by ImranNawar** [roshan1337d/coding-contests-companion#36]
Hi there!
I recommend adding a **CODE_OF_CONDUCT.md** file to your repository. This file would serve as a guide for potential contributors, providing them with a clear set of expectations, guidelines, and behavior standards for participating in your project. It plays an essential role in creating a welcoming and inclusive environment for everyone involved.

I would like to work on this issue. Please assign it to me under **GSSoC'23**.

Thank you!

**Comment by roshan1337d** [comment]
Assigned this to you 🚀

Specify the less obvious things rather than common decent human values that mostly everyone does anyway.
