### ISSUE TITLE
Add support for HackerEarth

### ISSUE THREAD

**Issue by roshan1337d** [roshan1337d/coding-contests-companion#4]
## What needs to be done

Create a `hackerEarth` function in the [scraping.js](https://github.com/roshan1337d/coding-contests-companion/blob/master/utility/scraping.js) file which returns an array of contest details from HackerEarth. You can use Axios to get the contest data as JSON from [here](https://www.hackerearth.com/chrome-extension/events). The contest data should be returned in the following format:

```js
{
    name: 'name_of_contest',
    url: 'link_to_the_contest',
    start: start_time_in_epoch_format,
    duration: duration_in_seconds
}
```

**Comment by saimaheshtaduri** [comment]
I  would like to contribute to this. assign to me. @roshan1337d

**Comment by roshan1337d** [comment]
@saimaheshtaduri Assigned this to you. Submit after the 1st of October if you want it to count towards the HacktoberFest 🚀

**Comment by roshan1337d** [comment]
PR submitted and approved
