### ISSUE TITLE
Remove some typos

### ISSUE THREAD

**Issue by RJ025** [roshan1337d/coding-contests-companion#46]
Hello @roshan1337d 
When clicked on setup-contests bot shows a message above get notified button it contains name of the contests which are are not present like kickstart
So I would like remove it and add contests name which are present like geeks for geeks 

![image](https://github.com/roshan1337d/coding-contests-companion/assets/93763090/7f00a229-d219-453b-addc-aa5fef9d5a2c)

Please assign it to me
Under GSSOC'23 tag

**Comment by roshan1337d** [comment]
Go ahead 👍
