### ISSUE TITLE
[GSSOC] add a comment on Problem of the day

### ISSUE THREAD

**Issue by vivxsdb** [roshan1337d/coding-contests-companion#49]
Generally, when we are given a problem of the day, we can leave a comment on how to solve the problem, and different users can share their solutions. This can be helpful for beginners who are just starting to learn coding. Can u please assign me under GSSOC'23

**Comment by vivxsdb** [comment]
1. !problem. When a user sends this command, the bot uses Puppeteer to scrape the website and retrieve the daily problem. The problem is then sent back to the channel using the message.channel.send() method
2.  !solution. When a user sends this command followed by their solution, the bot sends a message thanking the user for sharing their solution
3. and then we will store the solution in the database and send on the channel

**Comment by KamalSritha-04** [comment]
Can you please assign me this issue under GSSOC'23?

**Comment by roshan1337d** [comment]
@vivxsdb Problem of the day is based on LeetCode daily problems and the users can refer to the discussion section there to send and find answers of other users.
