### ISSUE TITLE
Convert normal messages into embed messages

### ISSUE THREAD

**Issue by roshan1337d** [roshan1337d/coding-contests-companion#5]
## What needs to be done

Convert all normal messages for [setup-contest](https://github.com/roshan1337d/coding-contests-companion/blob/master/commands/setup-contest.js), [setup-problem](https://github.com/roshan1337d/coding-contests-companion/blob/master/commands/setup-problem.js), and [stop](https://github.com/roshan1337d/coding-contests-companion/blob/master/commands/stop.js) commands into embed messages. The embed should have 1089DF colour, the original message as the description, and an appropriate title in uppercase. If you feel like you can make the messages more descriptive, feel free to do so.

**Comment by basil08** [comment]
Hi @roshan1337d , I would like to work on this :)

**Comment by roshan1337d** [comment]
@basil08 Assigned this to you 🚀

**Comment by roshan1337d** [comment]
@basil08 you still want to work on this one?

**Comment by basil08** [comment]
Yes, I'll open a PR by tomorrow

**Comment by roshan1337d** [comment]
@basil08 if you're occupied, I can reassign this to someone else? Let me know

**Comment by devsargam** [comment]
@roshan1337d if this is still incomplete. Assign me please!

**Comment by roshan1337d** [comment]
@devsargam you got it 🚀
Happy hacktober :)
