### ISSUE TITLE
Adding contributors graph in the readme

### ISSUE THREAD

**Issue by mukul314** [roshan1337d/coding-contests-companion#55]
Having a contributor graph in the readme file will make it more informative and it will also boost the morale of all the contributors who have made valuable additions to this project.  Current contributor information is not looking that attractive, logos of profiles can be added to the contributor graph.

Something like this maybe??
<img width="492" alt="2023-06-07 09_37_33-JasonDsouza212_free-hit_ 🏏Free-Hit is an application that is used to search for" src="https://github.com/roshan1337d/coding-contests-companion/assets/76463001/c983b256-d859-4487-99ab-8879bda683de">

@roshan1337d , please assign me this issue under GSSOC'23.

**Comment by roshan1337d** [comment]
There is an open pull request with this already waiting for some modifications to be merged.
