### ISSUE TITLE
Add New issue template

### ISSUE THREAD

**Issue by Abhinavcode13** [roshan1337d/coding-contests-companion#56]
Issue templates ensure that all issues reported in a repository follow a consistent structure and format. They provide a predefined outline with sections and prompts for essential information, ensuring that users provide consistent and standardized details when creating issues.

**Comment by Abhinavcode13** [comment]
Please assign me this issue under gssoc @roshan1337d

**Comment by roshan1337d** [comment]
There is an open issue for this with someone assigned already #53

**Comment by Abhinavcode13** [comment]
Bro that is opened there is no update still @roshan1337d  I will make a PR in a hour , it's not a hard task
