### ISSUE TITLE
Create templates for better maintaining

### ISSUE THREAD

**Issue by Dun-sin** [roshan1337d/coding-contests-companion#6]
I saw this project is open to contributions, and it doesn't have Pull request and issue templates, it makes it easier for you to maintain your projects.

Here are links for reference: 
[Pull Request Template](https://learn.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops)
[Pull Request and Issue Template](https://bakingclouds.com/multiple-template-choices/)

**Comment by roshan1337d** [comment]
Good point, thanks for the suggestion.
I will do that soon 👍
